### ISSUE TITLE
Health Service is not working

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-office-workflow#525]
Seems that the health service is not working correctly....

```
 livenessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9990/health | grep -q '\"name\":\"imixs-workflow\",\"status\":\"UP\"'"]
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
```
